import { AppData } from "../types";

export const INITIAL_APP_DATA: AppData = {
  Fr_InputList: [],
  Timesheet_InputList: [],
  Final_Centers: {
    headers: [
      "No",
      "L07",
      "Mã AE",
      "Business",
      "ID Number",
      "Full name",
      "Salary Scale",
      "From",
      "To",
      "Bank Account Number",
      "Bank Name",
      "CITAD code",
      "TAX CODE",
      "Contract No",
      "CHARGE TO LXO",
      "CHARGE TO EC",
      "CHARGE TO PT-DEMO",
      "Charge MKT Local",
      "Charge Renewal Projects",
      "Charge Discovery Camp",
      "Charge Summer Outing",
      "TOTAL PAYMENT",
    ],
    data: [],
  },
  Final_AE: {
    headers: [
      "No",
      "Mã AE",
      "Business",
      "ID Number",
      "Full name",
      "TOTAL PAYMENT",
    ],
    data: [],
  },
  Bank_North_AE: {
    headers: [
      "No",
      "L07",
      "Business",
      "ID Number",
      "Full name",
      "Bank Account Number",
      "TOTAL PAYMENT",
      "LOẠI CK",
      "Payment details",
    ],
    data: [],
  },
  Sheet1_AE: {
    headers: [
      "No",
      "ID Number",
      "Full name",
      "Salary Scale",
      "From",
      "To",
      "Bank Account Number",
      "Bank Name",
      "CITAD code",
      "TAX CODE",
      "Contract No",
      "CHARGE TO LXO",
      "CHARGE TO EC",
      "CHARGE TO PT-DEMO",
      "Charge MKT Local",
      "Charge Renewal Projects",
      "Charge Discovery Camp",
      "Charge Summer Outing",
      "TOTAL PAYMENT",
      "L07",
      "Business",
    ],
    data: [],
  },
  Hold_AE: {
    headers: [
      "No",
      "ID Number",
      "Full name",
      "L07",
      "Business",
      "Bank Account Number",
      "Bank",
      "Tháng",
      "LOẠI CK",
      "TAX CODE",
      "Contract No",
      "TOTAL PAYMENT",
      "CENTER NOTE",
      "Sheet Source",
      "Note",
    ],
    data: [],
  },
  SoSanh_AE: {
    headers: [
      "ID Number",
      "Full name",
      "Sheet 1 AE",
      "Bank North AE",
      "Chênh Lệch",
    ],
    data: [],
  },
  AuditReport: {
    headers: [
      "Khóa Cột So Sánh",
      "Mã AE",
      "Total (Bảng 1)",
      "Total (Bảng 2)",
      "Chênh Lệch",
    ],
    data: [],
  },
  BankExport: {
    headers: [
      "Payment Serial Number",
      "Transaction Type Code",
      "Payment Type",
      "Customer Reference No",
      "Beneficiary Account No.",
      "Beneficiary Name",
      "Document ID",
      "Place of Issue",
      "ID Issuance Date",
      "Beneficiary Bank Swift Code / IFSC Code",
      "Transaction Currency",
      "Payment Amount",
      "Charge Type",
      "Payment details",
      "Beneficiary - Nick Name",
      "Beneficiary Addr. Line 1",
      "Beneficiary Addr. Line 2",
    ],
    data: [],
  },
  CustomReport: {
    headers: ["STT", "Trung Tâm", "Tháng", "Tổng tiền", "Ghi chú"],
    data: [],
  },
  AE_Map: {},
  AE_AutoMappingRules: [],
  Ae_Global_Inputs: [],
  PivotConfig: {
    headers: { Business: "Business", L07: "Mã AE", GRAND_TOTAL: "GRAND TOTAL" },
    chargeCols: [
      { key: "CHARGE TO LXO", label: "CHARGE TO LXO", code: "04" },
      { key: "CHARGE TO EC", label: "CHARGE TO EC", code: "PSZINT-A1" },
      {
        key: "CHARGE TO PT-DEMO",
        label: "CHARGE TO PT-DEMO",
        code: "MAZINT-E1-LDEM01",
      },
      { key: "Charge MKT Local", label: "CHARGE MKT LOCAL", code: "E1" },
      {
        key: "Charge Renewal Projects",
        label: "CHARGE RENEWAL PROJECTS",
        code: "EFZZZZ-R3",
      },
      {
        key: "Charge Discovery Camp",
        label: "CHARGE DISCOVERY CAMP",
        code: "",
      },
      { key: "Charge Summer Outing", label: "CHARGE SUMMER OUTING", code: "" },
    ],
  },
  Q_Staff: [],
  Q_Salary_Scale: [],
  Q_Roster: [],
  Q_Cache: [],
  Timesheet_Dates: { from: "", to: "" },
  Timesheets: [],
  TA_Employee_Summary: { headers: [], data: [] },
  TA_Center_Summary: { headers: [], data: [] },
  Q_TeacherHours: [],
  Q_TeacherHoursFileName: "",
};
